def test_main():
    print(this is supposed to fail a unit test)
    return 69
    
   
